url: "https://blog.passos.me"
baseurl: "/btest" # the subpath of your site, e.g. /blog
title: "Daniel Passos"
description: "A deep dive into modern mobile development, Kotlin Multiplatform, and Compose. Insights, experiments, and real-world lessons for engineers building the next generation of apps."

permalink: /:title

plugins:
  - jekyll-archives
  - jekyll-feed
  - jekyll-seo-tag

jekyll-archives:
  enabled:
    - categories
    - tags
  permalinks:
    category: '/categories/:name/'
    tag: '/tags/:name/'
  layouts:
    category: category
    tag: tag

jekyll_feed:
  title: "Daniel Passos"
  description: "A deep dive into modern mobile development, Kotlin Multiplatform, and Compose. Insights, experiments, and real-world lessons for engineers building the next generation of apps."
  author: "Daniel Passos"
  feed:
    icon: /images/icon.png
    logo: /images/logo.png
