url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "" # the name of your site, e.g. ACME Corp.

permalink: /:title

plugins:
  - jekyll-archives
  - jekyll-feed
  - jekyll-seo-tag

jekyll-archives:
  enabled:
    - categories
    - tags
  permalinks:
    category: '/categories/:name/'
    tag: '/tags/:name/'
  layouts:
    category: category
    tag: tag
